### ISSUE TITLE
obsolete routingpy on conda-forge

### ISSUE THREAD

**Issue by mbarison** [gis-ops/routingpy#134]
Hi,

It seems like on `conda-forge` you can only get routingpy up to version 0.3.3

Whereas, to install the latest version, you need to use a custom channel:
https://anaconda.org/sfe1ed40/routingpy

Why is that? Can you please upload v.1.3.0 to `conda-forge`? Not all users have access to custom channels.

Thanks!

**Comment by chrstnbwnkl** [comment]
Yeah I remember there were some hurdles involved in publishing on conda-forge channels. We are not really committed to fixing this.
