### ISSUE TITLE
Support Graphhopper's POST Route Endpoint

### ISSUE THREAD

**Issue by jan-bausch** [gis-ops/routingpy#90]
Graphhopper supports both a [`GET`](https://docs.graphhopper.com/#operation/getRoute) and a [`POST`](https://docs.graphhopper.com/#operation/postRoute) directions endpoint. However, the `GET` endpoint has some limitations:

> For the GET request you specify the parameters in the URL and can try it directly in every browser. However, it has some disadvantages when using many points (URL length limit) and the [custom_model Feature](https://docs.graphhopper.com/#section/Custom-Model) cannot be used. Therefore, our recommended endpoint is the [POST route endpoint](https://docs.graphhopper.com/#operation/postRoute).

(Quote from the [Graphhopper docs](https://docs.graphhopper.com/#operation/getRoute))

Currently, routingpy only supports the `GET` endpoint. It would be cool to use `POST`, to be able to set custom models!

**Comment by nilsnolde** [comment]
Jep right. They must've added POST a while ago. They went through 6 major versions in the past 2 years, can't keep up with that;)

We hardly ever work with Graphhopper, but would appreciate a PR fixing it.

**Comment by jan-bausch** [comment]
Do you prefer

a) replacing the GET with the POST request alltogether, or
b) adding an optional parameter to use the POST endpoint?

**Comment by jan-bausch** [comment]
Intuitively, I'd go for a), as the endpoints should be interchangeable. Whats your opionion?

**Comment by jan-bausch** [comment]
I agree 👍 
Based on the docs, there are no drawbacks, and POST is clearly recommended.

**Comment by jan-bausch** [comment]
Created https://github.com/gis-ops/routingpy/pull/91

**Comment by jan-bausch** [comment]
Any chance for a quick review, @nilsnolde ?

**Comment by nilsnolde** [comment]
was done in #91 & #92 , thanks again:)
