### ISSUE TITLE
GraphHopper "profile" is set under "vehicle"

### ISSUE THREAD

**Issue by Serphentas** [gis-ops/routingpy#93]
#### Here's what I did

A simple query, such as:

```python
client.directions(locations=[...],[...]],instructions=False,elevation=True,profile="car",**{"avoid":"motorway;ferry"})
```

---
#### Here's what I got

No "profile" set, but a "vehicle" that GraphHopper doesn't accept:

```
    raise exceptions.RouterApiError(status_code, body)
routingpy.exceptions.RouterApiError: 400 ({'message': 'profile parameter required', 'hints': [{'message': 'profile parameter required', 'details': 'java.lang.IllegalArgumentException'}]})
```

---
#### Here's what I was expecting

The "profile" key to be set accordingly

---
#### Here's what I think could be improved

This [line](https://github.com/gis-ops/routingpy/blob/2608d2ae3b2c28f35cf74e63bf56d876ff21b3eb/routingpy/routers/graphhopper.py#L273) should be changed from

```python
params = {"vehicle": profile}
```

to

```python
params = {"profile": profile}
```

since no "vehicle" key exists in the GraphHopper [API documentation](https://docs.graphhopper.com/#operation/postRoute!path=profile&t=request).

**Comment by nilsnolde** [comment]
Huh.. we just had a PR fixing some other GH things, I can’t imagine that didn’t work a few weeks back. Did they release another major version and changed it?

**Comment by nilsnolde** [comment]
Jep, GH 7.0 removed the `vehicle` parameter: https://github.com/graphhopper/graphhopper/blob/master/CHANGELOG.md#70-14-mar-2023

**Comment by Serphentas** [comment]
Good catch. Shall I go ahead with a PR ? I'm thinking about a `version` parameter for the client initialization, or perhaps just the `directions` method, to switch between `vehicle` and `profile`.

**Comment by nilsnolde** [comment]
> Shall I go ahead with a PR 

that’d be great thanks! 

> I'm thinking about a version parameter for the client initialization

That’d be noble:) But I think we should just support whatever’s on their public API, since that’s a slippery slope. GH has twice a year major version upgrades currently, too much of a maintenance hassle to support all their deprecations to be honest.

**Comment by Serphentas** [comment]
See above, I followed your advice and simply replaced the key with no backwards support.

**Comment by nilsnolde** [comment]
Done in #94
